config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:index]

  root to: 'pages#home', as: :home
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Users
  get 'board', to: 'users#activity', as: :activity

  get 'get_json', to: 'goals#get_json'

  # Goals
  resources :goals, shallow: true do
    resources :tasks
      # member do
      #   patch :mark_as_done
      # end
  end

  resources :goals do
    resources :tasks, only: :show
  end
  get 'goals/category/:category', to: 'goals#by_category', as: :by_category
  get 'goals/status/:maturity', to: 'goals#by_status', as: :by_status
  # Tasks
  get '/tasks', to: 'tasks#all_tasks'
  patch '/tasks_update/:id', to: 'tasks#update_task'
  get '/calendar', to: 'tasks#calendar'
  get '/stats', to: 'tasks#stats'

  # Users - El nickname es unico para cada usuario
  resources :users, only: %i[show]
  # get 'u/:nickname', to: 'users#show'

  patch "goals/:goal_id/:task_id/mark", to: "tasks#done_task"
end

app/models/task.rb
class Task < ApplicationRecord
  include PgSearch::Model

  after_create :goal_maturity!
  after_update :goal_maturity!

  belongs_to :goal
  has_one_attached :photo
  has_rich_text :rich_body

  pg_search_scope :search, against: %i[name description priority difficulty], using: { tsearch: { prefix: true } }

  validates :name, :status, :priority, :difficulty, :goal, :due_date, presence: true
  validates :name, length: { minimum: 5 }
  validates :description, length: { maximum: 200 }

  enum status: { not_started: 0, in_progress: 1, done: 2 }
  enum priority: { low: 0, medium: 1, high: 2 }
  enum difficulty: { easy: 0, meddium: 1, hard: 2 }

  def user
    goal.user
  end

  def start_time
    due_date
  end

  def completion_date!
    update_attribute(:completion_date, Time.now)
  end

  def goal_maturity!
    tasks_count = goal.tasks.count
    done_tasks_fraction = goal.tasks.done.count.fdiv(tasks_count)
    if done_tasks_fraction < 0.25
      goal.update_attribute(:maturity, 0)
    elsif done_tasks_fraction >= 0.25 && done_tasks_fraction <= 0.75
      goal.update_attribute(:maturity, 1)
    else
      goal.update_attribute(:maturity, 2)
      goal.update_attribute(:completion_date, DateTime.current) if done_tasks_fraction.to_d == 1.0.to_d
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_goal, only: %i[new create index]
  before_action :set_task, only: %i[show edit update destroy update_task]
  before_action :goal_policy, only: %i[index new]
  before_action :task_policy, only: %i[show edit delete]

  def index
    @tasks = @goal.tasks
    @todo = @tasks.not_started
    @doing = @tasks.in_progress
    @done = @tasks.done
    @tasks = @tasks.search(params[:query]) if params[:query].present?
    @pagy, @tasks = pagy @tasks.reorder(sort_column => sort_direction), items: params.fetch(:count, 10)
  end

  def all_tasks
    @tasks = current_user.tasks
    @tasks = @tasks.search(params[:query]) if params[:query].present?
    @pagy, @tasks = pagy @tasks.reorder(sort_column => sort_direction), items: params.fetch(:count, 10)
  end

  def show
  end

  def new
    @task = Task.new
    redirect_to activity_path, alert: "Oh oh!, this tree is already dead!" if @goal.dead?
  end

  def create
    @task = Task.new(task_params)
    @task.goal = @goal
    @task.save
    if @task.save
      redirect_to goal_path(@task.goal), notice: "Ok!"
    else
      render :new, status: :unprocessable_entity, alert: "Change a few things and try submitting again"
    end
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task), notice: "Your changes have been saved successfully"
  end

  def update_task
    @task.update(task_params)
    @task.completion_date! if task_params["status"] == "done"
  end

  def calendar
    @tasks = current_user.tasks
  end

  def destroy
    @task.destroy
    redirect_to goal_path(@task.goal), status: :see_other, notice: "Your tasks has been deleted"
  end

  def stats
    @tasks = current_user.tasks
    @task = Task.new
    @tasks = Task.all
    @goals= Goal.all
    @goal = Goal.new
  end

  # Metodos de datatable
  def sort_column
    %w[name priority difficulty due_date].include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def done_task
    task = Task.find(params[:task_id])
    if task.done?
      task.not_started!
    else
      task.done!
    end
    redirect_to goal_path(task.goal_id)
  end

  # Metodos privados
  private

  def task_params
    params.require(:task).permit(:name, :description, :status, :priority, :difficulty, :due_date, :goal_id, :review)
  end

  def set_goal
    @goal = Goal.find(params[:goal_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_policy
    set_task
    redirect_to activity_path, alert: "You don't have permission to access this page" unless current_user == @task.user
  end

  def goal_policy
    set_goal
    redirect_to activity_path, alert: "You don't have permission to access this page" unless current_user == @goal.user
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form_create_only_task.html.erb
<div class="row justify-content-center mx-auto">

        <%= simple_form_for [@goal, @task] do |f| %>


          <div class="row p-2 rounded-5 mb-3 bg-success text-dark bg-opacity-10">
            <div class="col-1 my-auto mx-auto d-flex align-items-center">
              <i class="fa-solid fa-list-check fs-1 mx-sm-1 mx-lg-5"></i>
            </div>
            <div class="col-10 pb-2">
              <h3>Create a new Task</h3>
                <div>
                <%= f.input :name, input_html: {class:"border-0 rounded-4 p-3"}, label:false, placeholder:"Enter task tittle..." %>
                </div>
                 <div class="row d-flex justify-content-end">
                    <%= f.submit class:"btn btn-dark rounded-4 col-sm-4 col-lg-3"%>
                </div>
            </div>
          </div>

  <% end %>
</div>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>" class="table-row d-flex justify-content-start shadow-sm py-1 border-bottom border-primary">
  <div class="table-cell d-inline-block text-truncate" style="width: 120%;">
    <%= link_to "#{task.name}" , task, class:"text-decoration-none text-white-smoke" %>
  </div>
  <div class="table-cell text-white-smoke" style="width: 60%;">
    <%= task.priority %>
  </div>

  <div class="table-cell text-white-smoke" style="width: 60%;">
    <%= task.difficulty %>
  </div>

  <div class="table-cell text-white-smoke d-flex" style="width: 60%;">

    <% if task.not_started? %>
      <span class="badge rounded-pill bg-danger text-dark"> <%= task.status %></span>
    <% elsif task.in_progress? %>
      <span class="badge rounded-pill bg-info text-dark"> <%= task.status %></span>
    <% else %>
      <span class="badge rounded-pill bg-success text-dark"> <%= task.status %></span>
    <% end %>

  </div>

  <div class="table-cell text-white-smoke" style="width: 60%;">
  <small> <%= task.due_date&.strftime("%d/%m/%y") %> </small>
  </div>

</div>

app/views/tasks/all_tasks.html.erb
<style>
 .pagy1 a {
    padding: 8px;
    text-decoration: none;
}
</style>

<%# Banner %>
    <div class="col-12 mb-1 bg-body sticky-top pb-3">
<!-- Button back -->
    <div class="back-btn mt-0">
      <%= link_to :back do%>
          <i class="fa-solid fa-circle-arrow-left fs-5" class="back-btn rounded-4" data-bs-toggle="tooltip" data-bs-placement="top" title="Go Back"></i>
      <% end %>
    </div>

    <div class="d-flex align-items-end mx-4 mb-3">
      <%= image_tag "all-list-tasks.svg", class: "img-fluid", width: "120px" %>
      <div class="ms-4">
        <h2 class="fw-bold">Tasks</h2>
        <p class="mb-0"> Focus on your next task to do! Here you can find all your task, look at their status, due date and labels</p>
      </div>
    </div>
  </div>

<div class="row mx-4 pb-5 mb-5">
  <div class="col-sm-12 col-lg-8 mx-auto rounded-4 bg-secondary">
    <div class="row d-flex justify-content-between bg-secondary rounded-4 p-md-1 mt-4">
      <%= form_with url: "", method: :get, data: {turbo_frame: "tasks", turbo_action: "advance"} do |form| %>
        <div class="row">
          <div class="col">
            <i class="fa-solid fa-magnifying-glass me-2"></i> <%= form.search_field :query, value: params[:query], oninput: "this.form.requestSubmit()", placeholder: "Search a task...", class:"border-end border-bottom border-primary border-2 bg-body text-light shadow-sm p-1 px-2 rounded-pill" %>
          </div>
          <div class="col d-flex justify-content-end">
            <p> Show <%= form.select :count, options_for_select([10, 25, 50, 100], class:"rounded-pill", selected: params[:count]), {}, { onchange: "this.form.requestSubmit()"} %> entries </p>
          </div>
        </div>
      <% end%>
      <%= turbo_frame_tag "tasks" do %>
        <div class="table mt-3">
          <div class="table-header-group d-flex">
            <%= sort_link_to "Name", ":name", class: "table-cell text-decoration-none", style:"width: 120%;", data: { turbo_action: "advance" } %>
            <%= sort_link_to "Priority", ":priority", class: "table-cell text-decoration-none", style:"width: 60%;", data: { turbo_action: "advance" }  %>
            <%= sort_link_to "Difficulty", ":difficulty", class: "table-cell text-decoration-none", style:"width: 60%;", data: { turbo_action: "advance" }  %>
            <%= sort_link_to "Status", ":status", class: "table-cell text-decoration-none", style:"width: 60%;", data: { turbo_action: "advance" }  %>
            <%= sort_link_to "Due Date", ":due_date", class: "table-cell text-decoration-none", style:"width: 60%;", data: { turbo_action: "advance" }  %>
          </div>
           <%= render @tasks %>
        </div>

        <div class="p-2 d-flex justify-content-end pagy1">
          <%#== pagy_nav @pagy, class:"d-flex justify-content-end " %>
          <% end %>
        </div>
      </div>
  </div>

  <div class="col-4 d-none d-lg-flex justify-content-end  rounded-4 mb-2  align-items-end">
    <%= image_tag "task-all-img.svg", class: "img-fluid", width: "300px" %>
</div>

</div>

app/views/tasks/calendar.html.erb
<%# Banner %>
  <div class="col-12 mb-2 bg-body sticky-top pb-4">
<!-- Button back -->
    <div class="back-btn">
      <%= link_to  :back do%>
          <i class="fa-solid fa-circle-arrow-left fs-5" class="back-btn rounded-4" data-bs-toggle="tooltip" data-bs-placement="top" title="Go Back"></i>
      <% end %>
    </div>

    <div class="d-flex align-items-end mx-4">
      <%= image_tag "calendar-title.svg", class: "img-fluid", width: "110px" %>
      <div class="ms-4">
        <h2 class="fw-bold">Task Calendar</h2>
        <p class=""> Stay up to date! check your tasks on the calendar and improve time management </p>
      </div>
    </div>
  </div>


<%= render 'tasks/partials/calendar_index' %>

app/views/tasks/edit.html.erb
<%= render 'tasks/partials/form_create_edit_task' %>

app/views/tasks/new.html.erb
<%= render 'tasks/partials/form_create_only_task' %>

app/views/tasks/show.html.erb
<div class="row px-3 justify-content-center ">
  <div class="row">
    <div class="col-sm-12 col-lg-6 px-lg-5 d-flex justify-content-end align-items-center">
      <%= link_to edit_task_path(@task), class: "text-decoration-none link-dark circle-icon me-2" do %>
        <i class="bi bi-pencil-square rounded-circle p-2 bg-primary fw-bold fs-5 shadow-sm bg-gradient"></i>
      <% end %>
      <%= link_to task_path(@task),
      class: "text-decoration-none link-dark circle-icon",
      data: { turbo_method: :delete, controller: 'sweetalert', action: "click->sweetalert#show", sweetalert_title_value: @task.name } do %>
        <i class="bi bi-trash3 rounded-circle p-2 bg-danger fw-bold fs-5 shadow-sm bg-gradient"></i>
      <% end %>
        <%= link_to goal_path(@task.goal), class: "btn btn-primary rounded-pill ms-2 text-dark" do %>
          <i class="fa-solid fa-grip"></i> Board
        <% end %>
    </div>
    <div class="col-sm-4 col-lg-2">
     <h4 class="text-white fw-bold px-0"> Your Goal: </h4>
    </div>
    <div class="colsm-8 col-lg-4">
      <h5 class="text-white d-flex justify-content-start px-0">  <%= link_to @task.goal.name, goal_path(@task.goal), class: "text-decoration-none" %></h5>
    </div>
  </div>
  <div class="col-sm-12 col-lg-5 my-3 p-4 rounded-4 bg-secondary shadow-sm">
    <h3 class="text-light fw-bold"><%= @task.name %></h3>
    <h5 class=""><%= @task.description  %></h5>
    <hr>
    <div class="row bg-body d-flex  align-items-center mb-2 rounded-4 p-1 mx-1 my-1">
      <div class="col-4">
        <h5 class="p-1 my-1">Status:</h5>
      </div>
      <div class="col-8 ">
        <% if @task.not_started? %>
          <span class="badge rounded-pill bg-danger text-dark py-1" style="width: 50%;"> <%= @task.status %></span>
        <% elsif @task.in_progress? %>
          <span class="badge rounded-pill bg-info text-dark py-1" style="width: 50%;"> <%= @task.status %></span>
        <% else %>
          <span class="badge rounded-pill bg-success text-dark py-1" style="width: 50%;"> <%= @task.status %></span>
        <% end %>
      </div>
    </div>
    <div class="row bg-body d-flex  align-items-center mb-2 rounded-4 p-1 mx-1 my-1">
      <div class="col-4 ">
        <h5 class="p-1 my-1">Difficulty:</h5>
      </div>
      <div class="col-8 ">
          <% if @task.easy? %>
            <span class="badge rounded-pill bg-danger text-dark py-1" style="width: 50%;"> <%= @task.difficulty %></span>
          <% elsif @task.meddium? %>
            <span class="badge rounded-pill bg-info text-dark py-1" style="width: 50%;"> <%= @task.difficulty %></span>
          <% else %>
            <span class="badge rounded-pill bg-success text-dark py-1" style="width: 50%;"> <%= @task.difficulty %></span>
          <% end %>
      </div>
    </div>
    <div class="row bg-body d-flex  align-items-center mb-2 rounded-4 p-1 mx-1 my-1">
      <div class="col-4 ">
        <h5 class="p-1 my-1">Created at:</h5>
      </div>
      <div class="col-8 ">
          <p class="p-1 my-1"><%= @task.created_at&.strftime("%d/%m/%y") %></p>
      </div>
    </div>
    <div class="row bg-body d-flex  align-items-center mb-2 rounded-4 p-1 mx-1 my-1">
      <div class="col-4 ">
        <h5 class="p-1 my-1">Due Date:</h5>
      </div>
      <div class="col-8 ">
          <p class="p-1 my-1"> <%= @task.due_date&.strftime("%d/%m/%y") %></p>
      </div>
    </div>
    <div class="row bg-body d-flex  align-items-center mb-2 rounded-4 p-1 mx-1 my-1">
      <div class="col-4 ">
        <h5 class="p-1 my-1">Completion Date:</h5>
      </div>
      <div class="col-8 ">
          <p class="p-1 my-1"> <%= @task.completion_date&.strftime("%d/%m/%y") %> </p>
      </div>
    </div>
  </div>
      <div class="col-sm-12 col-lg-6 pe-0">
        <%= render 'tasks/partials/richtext_task' %>
      </div>
  </div>
</div>

app/views/tasks/stats.html.erb
<%# Banner %>
<div class="row pb-3 sticky-top">
  <div class="col-12 mb-1 bg-body pb-3">
  <!-- Button back -->
    <div class="back-btn">
      <%= link_to  :back do%>
          <i class="fa-solid fa-circle-arrow-left fs-5" class="back-btn rounded-4" data-bs-toggle="tooltip" data-bs-placement="top" title="Go Back"></i>
      <% end %>
    </div>
    <div class="d-flex align-items-end">
      <%= image_tag "stats-title.svg", class: "img-fluid", width: "110px" %>
      <div class="ms-4">
        <h2 class="fw-bold">Stats</h2>
        <p class=""> Measure your progress! Here you can constantly see your statistics</p>
      </div>
    </div>
  </div>
</div>



<div class="row bg-red order border-2">
  <div class="col-sm-12 col-lg-7">

    <div class="row my-auto align-items-center">

<!-- de camilo -->

        <div class="row g-3 my-2">

          <div class="col-sm-12 col-xl-4 mb-1 mt-3">
            <div class="rounded-4 bg-secondary">
              <div class="row g-0 justify-content-between">
                <div class="col-6 d-flex align-items-center">
                  <div class="card-body text-center">
                    <h5 class="card-title text-light">Not started</h5>
                  </div>
                </div>

                <div class="col-6 containerpb">
                  <div class="card notscale rounded-4 border-0 p-1">
                    <div class="percent" style="--clr:#7ed6df;--num:<%= percentage_not_started %>">
                      <div class="dot"></div>
                      <svg>
                          <circle cx="50" cy="50" r="50"></circle>
                          <circle cx="50" cy="50" r="50"></circle>
                      </svg>
                      <div class="number">
                      <h2> <%= percentage_not_started %> <span>%</span></h2>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </div>

          <div class="col-sm-12 col-xl-4 mb-1 mt-3">
            <div class="rounded-4 bg-secondary p-1">
              <div class="row g-0 justify-content-between">
                <div class="col-6 d-flex align-items-center">
                  <div class="card-body text-center">
                    <h5 class="card-title text-light">In progress</h5>
                  </div>
                </div>

                <div class="col-6 containerpb">
                  <div class="card notscale rounded-4 border-0">
                    <div class="percent" style="--clr:#686de0;--num:<%= percentage_in_progress %>">
                      <div class="dot"></div>
                      <svg>
                          <circle cx="50" cy="50" r="50"></circle>
                          <circle cx="50" cy="50" r="50"></circle>
                      </svg>
                      <div class="number">
                          <h2> <%= percentage_in_progress %> <span>%</span></h2>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </div>

          <div class="col-sm-12 col-xl-4 mb-1 mt-3">
            <div class="rounded-4 bg-secondary p-1">
              <div class="row g-0 justify-content-between">
                <div class="col-6 d-flex align-items-center">
                  <div class="card-body text-center">
                    <h5 class="card-title text-light">Done</h5>
                  </div>
                </div>

                <div class="col-6 containerpb">
                  <div class="card notscale rounded-4 border-0">
                    <div class="percent" style="--clr:#badc58;--num:<%= percentage_done %>">
                      <div class="dot"></div>
                      <svg>
                          <circle cx="50" cy="50" r="50"></circle>
                          <circle cx="50" cy="50" r="50"></circle>
                      </svg>
                      <div class="number">
                          <h2> <%= percentage_done %> <span>%</span></h2>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </div>

        </div>

<!-- fin de camilo -->

      <div class="col bg-secondary rounded-4 m-2 fs-1 p-2 my-lg-4">
        <div class="row">
          <div class="col-6 px-lg-6 d-flex align-items-center">
          <h5>Total Completed Tasks</h5>
          </div>
            <div class="col-sm-12 col-lg-6 d-flex justify-content-center px-5 align-items-center">

              <div class="class text-primary px-lg-2">
                <%= current_user.tasks.done.count %>
              </div>
              <i class="fa-solid fa-trophy  text-warning p-2"></i>
            </div>
        </div>
      </div>

      <div class="col bg-secondary rounded-4 m-2 fs-1 p-2 my-4">
        <div class="row">
          <div class="col-6 px-lg-6 d-flex align-items-center">
          <h5>Total Completed Goals</h5>
          </div>
            <div class="col-sm-12 col-lg-6 d-flex justify-content-center px-5 align-items-center">

              <div class="class text-primary px-lg-2">
                <%= current_user.goals.adult.count %>
              </div>
              <i class="fa-solid fa-trophy  text-warning p-2"></i>
            </div>
        </div>
      </div>

    </div>

  </div>


  <div class="col-sm-12 col-lg-5 p-2">

    <h5>All your tasks by status</h5>
      <div class="col bg-secondary rounded-4 p-2">
      <%= pie_chart current_user.tasks.group(:status).count, download: true, colors: ["#ff7979", "#badc58","#7ed6df"], empty: "Oops you haven't any task to see here!" %>
      </div>

  </div>


    <div class="row my-3">
      <div class="col-sm-12 col-lg-6">
        <h5>All your goals by category</h5>
        <div class="col bg-secondary rounded-4">
        <%= column_chart current_user.goals.group(:category).count, download: true, colors: ["#7ed6df"], empty: "Oops you haven't any goal to see here!"%>
        </div>

      </div>



      <div class="col-sm-12 col-lg-6">

        <h5>Tasks Completed in this month</h5>
          <div class="col bg-secondary rounded-4">
          <%= line_chart current_user.tasks.group_by_day(:completion_date, range: 1.month.ago).count,  download: true, colors: ["#686de0"], library: {backgroundColor: "#262638"}, empty: "Oops you aren't completed any task this month!"  %>
          </div>

      </div>
    </div>

</div>








<div class="row my-3 justify-content-center">
  <div class="col-sm-12 col-lg-4 p-2">
    <h5> Goals by Maturity level</h5>
    <div class="col bg-secondary rounded-4 p-2">
      <%= pie_chart current_user.goals.group(:maturity).count, donut: true, download: true, colors: ["#686de0", "#f6e58d","#7ed6df"], empty: "Oops you haven't any goal to see here!" %>
    </div>

  </div>



  <div class="col-sm-12 col-lg-4 p-2">
    <h5> Tasks by Difficulty level</h5>
      <div class="col bg-secondary rounded-4 p-2">
        <%= column_chart current_user.tasks.group(:difficulty).count, download: true, colors: ["#badc58"], empty: "Oops you haven't any goal to see here!"%>
      </div>
  </div>


  <div class="col-sm-12 col-lg-4 p-2">
    <h5> Tasks by Priority level</h5>
      <div class="col bg-secondary rounded-4 p-2">
        <%= line_chart current_user.tasks.group(:priority).count, download: true, colors: ["#7ed6df"], empty: "Oops you haven't any goal to see here!" %>
      </div>
  </div>


</div>