config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:index]

  root to: 'pages#home', as: :home
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Users
  get 'board', to: 'users#activity', as: :activity

  get 'get_json', to: 'goals#get_json'

  # Goals
  resources :goals, shallow: true do
    resources :tasks
      # member do
      #   patch :mark_as_done
      # end
  end

  resources :goals do
    resources :tasks, only: :show
  end
  get 'goals/category/:category', to: 'goals#by_category', as: :by_category
  get 'goals/status/:maturity', to: 'goals#by_status', as: :by_status
  # Tasks
  get '/tasks', to: 'tasks#all_tasks'
  patch '/tasks_update/:id', to: 'tasks#update_task'
  get '/calendar', to: 'tasks#calendar'
  get '/stats', to: 'tasks#stats'

  # Users - El nickname es unico para cada usuario
  resources :users, only: %i[show]
  # get 'u/:nickname', to: 'users#show'

  patch "goals/:goal_id/:task_id/mark", to: "tasks#done_task"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :goals, dependent: :destroy
  has_many :tasks, through: :goals
  has_one_attached :photo
  has_many :notifications, as: :recipient

  # validates :first_name, :last_name, presence: true, length: { minimum: 2 }
  # validates :nickname, uniqueness: true

  # Scopes
  def goal_categories
    goals.distinct.pluck(:category)
  end

  # def baby_goals_count
  #   goals.baby.count
  # end

  # def young_goals_count
  #   goals.young.count
  # end

  # def adult_goals_count
  #   goals.adult.count
  # end

  def baby_goals_fraction
    goals.present? ? goals.baby.count.fdiv(goals.count) : 0
  end

  def young_goals_fraction
    goals.present? ? goals.young.count.fdiv(goals.count) : 0
  end

  def adult_goals_fraction
    goals.present? ? goals.adult.count.fdiv(goals.count) : 0
  end

  def upcoming_tasks
    tasks.not_done.where('due_date >= ?', Date.today)
  end

  def last_updated_goals
    goals.order(updated_at: :desc).first(3)
  end

  def tasks_grouped_by_day
    upcoming_tasks.order(:due_date).group_by { |t| t.due_date.strftime("%e %B") }
  end

  def not_started_tasks_fraction
    tasks.present? ? tasks.not_started.count.fdiv(tasks.count) : 0
  end

  def in_progress_tasks_fraction
    tasks.present? ? tasks.in_progress.count.fdiv(tasks.count) : 0
  end

  def done_tasks_fraction
    tasks.present? ? tasks.done.count.fdiv(tasks.count) : 0
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.full_name = auth.info.name # assuming the user model has a name
      user.avatar_url = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  def google_oauth2
    user = User.from_omniauth(auth)

    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] =
        t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || activity_path
  end

  private

  # def from_google_params
  #   @from_google_params ||= {
  #     uid: auth.uid,
  #     email: auth.info.email,
  #     full_name: auth.info.name,
  #     avatar_url: auth.info.image
  #   }
  # end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  def update_resource(resource, params)
    if resource.provider == 'google_oauth2'
      params.delete('current_password')
      resource.password = params['password']

      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_update_path_for(resource)
    flash[:notice] = "Account succesfully updated"
    user_path(resource)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || activity_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def activity
    @user = current_user
    @tasks = @user.tasks
    @goals = @user.goals

    # Upcoming tasks
    @upcoming_tasks_day = @user.tasks_grouped_by_day.keys[0]
    @upcoming_tasks = @user.tasks_grouped_by_day.values[0]

    # Percentages
    @baby_percentage = (@user.baby_goals_fraction * 100).round
    @young_percentage = (@user.young_goals_fraction * 100).round
    @adult_percentage = (@user.adult_goals_fraction * 100).round

    # Tasks counts
    @not_started_tasks = @user.tasks.not_started.count
    @in_progress_tasks = @user.tasks.in_progress.count
    @done_tasks = @user.tasks.done.count

    @last_updated_goals = @user.last_updated_goals
    dead_count = 0
    @goals.each { |goal| dead_count += 1 if goal.dead? }
    @dead_count = dead_count
    @alive_count = @goals.count - dead_count
    if @goals.present?
      @alive_percentage = (@alive_count.fdiv(@goals.count) * 100).round
      @dead_percentage = (@dead_count.fdiv(@goals.count) * 100).round
    end
    @goal_information = @goals.map do |goal|
      {
        id: goal.id,
        name: goal.name,
        description: goal.description,
        category: goal.category,
        date: goal.completion_date
      }
    end
  end

  def show
    @user = current_user
  end

  # def send_notification
  #   current_user.goals.each do |goal|
  #     if goal.dying? || goal.dead?
  #       goal.notify_user
  #     end
  #   end
  # end
end

app/helpers/users_helper.rb
module UsersHelper
  # Necesitamos agregar los siguientes metodos que sobreescriben algunos metodos de
  # la gema Devise
  def resource_name
    :user
  end

  def resource
    # @resource ||= User.new
    @resource ||= current_user
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def user_has_name?
    current_user.full_name || current_user.nickname
  end

end

app/views/users/_card_goal_board.html.erb
<div class="border-2 border-bottom border-end border-primary card p-2 bg-secondary my-2 rounded-4 border-0 shadow-sm notscale align-items-stretch">
  <img src="https://i.pinimg.com/736x/b9/5f/28/b95f288699b2dec39cc6e688a45e92df--arte-fractal-colour-wheel.jpg" class="card-img-top rounded-4 img-fluid" alt="arbol">
  <%# <div class="bg-cover img card-img-top" style="background-image: url('https://i.pinimg.com/736x/b9/5f/28/b95f288699b2dec39cc6e688a45e92df--arte-fractal-colour-wheel.jpg')"></div> %>

  <div class="card-body text-light p-1 py-2">
    <div class="d-flex flex-column align-items-bottom">
      <h5 class="fw-bold card-title fs-08 text-center" style="height: 45px;"><%= title_stylized(goal.name) %></h5>
    </div>
  </div>
</div>

app/views/users/_card_goal_modal.html.erb
<div class="card border-0 rounded-4 notscale mb-2 bg-secondary border-2 border-bottom border-end border-primary">
  <div class="mx-0 card-body d-flex align-items-center justify-content-start py-1">
    <%#= image_tag "completed_tasks.svg", width: "75px", class: "me-3 my-1" %>
    <img src="<%= health_goal_image(goal.dead?, goal.maturity) %>" class="card-img-left rounded-4 img-fluid me-3 my-1" style="width: 100px" alt="arbol">
    <div class="">
      <h6 class="mb-2 fw-bold"><%= goal.name %></h6>
      <h6 class="mb-1 fs-07 opacity-75">Created at: <%= date_stylized(goal.created_at) %></h6>
      <h6 class="mb-1 fs-07 opacity-75">Last change at: <%= date_stylized(goal.updated_at) %></h6>
    </div>
  </div>
</div>

app/views/users/_carousel_and_modal.html.erb
<div id="carouselCards" class="carousel slide" data-controller="carousel-cards" data-bs-interval="false" data-ride="carousel" data-pause="hover">

  <div class="carousel-inner p-1 px-5">
    <% i = 0 %>
    <%#= Iteramos sobre listas de maximo 4 elementos %>
    <% @goals.last(12).each_slice(4) do |sublist| %>
    <%# Se crea un item del carousel con estos elementos %>
      <div class="carousel-card carousel-item" data-carousel-cards-target="item">
        <div class="row g-3">
        <%# Presentamos el objeto en forma de card %>
          <% sublist.each do |goal| %>
            <div class="col-6 col-md-3">
            <div class="" data-controller="goal-modal" data-bs-toggle="modal" data-bs-target="#modalGoal" data-bs-goal-information="<%= @goal_information.to_json %>" data-goal-modal-information-value="<%= @goal_information.to_json %>">
            </div>
              <%= render "card_goal_board", goal: goal %>
            <% i += 1 %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <%# Si se muestran mas de 6 elementos entonces los controles del carousel son visibles %>
  <% unless @goals.size <= 6 %>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselCards" data-bs-slide="prev">
      <span class="carousel-control-prev-icon rounded-4" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselCards" data-bs-slide="next">
      <span class="carousel-control-next-icon rounded-4" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  <% end %>
</div>

app/views/users/_ghost_card.html.erb
<%= link_to goals_path, class: "text-decoration-none" do %>
<div class="bg-cover border-2 border-bottom border-end border-primary card p-2 bg-secondary my-2 rounded-4 border-0 shadow-sm notscale align-items-stretch" style="background-image: url(https://i.pinimg.com/564x/f2/52/fa/f252fa96c51dd1cb0ac71f85858632db.jpg)">
  <h5 class="m-0 p-0">See all goals</h5>
</div>
<% end %>

app/views/users/_search_form.html.erb
<%= form_with url: goals_path, method: :get, html: { class: 'mb-5', data: { refresh_list_target: 'form' } } do |f| %>
  <%= f.text_field :query,
                    class: "form-control",
                    placeholder: 'Type something',
                    value: params[:query],
                    data: {
                    refresh_list_target: 'searchInput',
                  } %>
  <% end %>

app/views/users/activity.html.erb
<style>
@media screen and (min-width: 800px) {
  .modal-dialog {
    margin-right: 0 !important;
    margin-top: 0 !important;
  }
}
</style>
<% if @user.goals.present? %>
<div class="row g-4 mb-5">
  <div class="col-md-8 order-1 order-md-0">
    <h5 class="pb-2 mb-3 border-bottom">Goals summary</h5>
    <div class="row gx-3">
      <div class="col-4 col-sm-4 align-items-stretch mb-2">
        <div class="card border-0 rounded-4 bg-secondary shadow-sm notscale" style="">
          <div class="card-body d-flex justify-content-between">
            <%= image_tag "babytree2.svg", class: "img-fluid d-none d-md-block", width: "90px" %>
            <div class="text-end">
              <p class="fs-3 m-0 mb-1"><%= @baby_percentage %>%</p>
              <p class="card-text fs-08 mb-1 fw-bold text-muted ">Baby trees</p>
              <div class=""><%= link_to "See goals", by_status_path(0), class: "rounded-pill text-decoration-none link-danger fs-07" %></div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-4 col-sm-4 align-items-stretch mb-2">
        <div class="card border-0 rounded-4 bg-secondary shadow-sm notscale" style="">
          <div class="card-body d-flex justify-content-between">
            <%= image_tag "babytree1.svg", class: "img-fluid d-none d-lg-block ms-2", width: "80px" %>

            <div class="text-end">
              <p class="fs-3 m-0 mb-1"><%= @young_percentage %>%</p>
              <p class="card-text fs-08 mb-1 fw-bold text-muted">Young trees</p>
              <div class=""><%= link_to "See goals", by_status_path(1), class: "rounded-pill text-decoration-none link-primary fs-07" %></div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-4 col-sm-4 align-items-stretch mb-2">
        <div class="card border-0 rounded-4 bg-secondary shadow-sm notscale" style="">
          <div class="card-body d-flex justify-content-between">
            <%= image_tag "japantree1.svg", class: "img-fluid d-none d-lg-block", width: "120px" %>
            <div class="text-end">
              <p class="fs-3 m-0 mb-1"><%= @adult_percentage %>%</p>
              <p class="card-text fs-08 mb-1 fw-bold text-muted">Adult trees</p>
              <div class=""><%= link_to "See goals", by_status_path(2), class: "rounded-pill text-decoration-none link-success fs-07" %></div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <h5 class="mt-3 pt-3 pb-2 mb-3 border-bottom">General activity</h5>
    <div class="row gx-3">
      <div class="col-4">
        <div class="mx-0 card rounded-4 border-0 bg-secondary notscale bg-cover" style="height: 100%; background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= health_goals_image_url%>)">
        </div>
      </div>
      <div class="mx-0 col-8">
        <div class="card notscale rounded-4 border-0 bg-secondary">
          <div class="card-body">
            <div class="mb-3">
            <div class="pb-3 d-flex justify-content-between align-items-center">
              <p class="m-0 fw-bold fst-italic">Goals</p>
              <%= link_to "Add a new goal", new_goal_path, class: "bg-gradient badge bg-primary p-1 px-2 link-dark rounded-pill text-decoration-none" %>
            </div>
                <div class="progress rounded-4 mb-2">
                  <div class="progress-bar bg-success" role="progressbar" aria-label="Segment one" style="width: <%= @alive_percentage %>%" aria-valuenow="<%= @alive_percentage %>" aria-valuemin="0" aria-valuemax="100"><span class="fs-07 fw-bold fst-italic text-dark px-2"><%= @alive_percentage %>%</span></div>
                  <div class="progress-bar bg-danger" role="progressbar" aria-label="Segment two" style="width: <%= @dead_percentage %>%" aria-valuenow="<%= @dead_percentage %>" aria-valuemin="0" aria-valuemax="100"><span class="fs-07 fw-bold fst-italic text-dark px-2"><%= @dead_percentage %>%</span></div>
                </div>
                <div class="d-flex justify-content-end align-items-center fs-07">
                  <div class="circle me-2 bg-success"></div><span class="fst-italic">Alive trees percentage</span>
                  <div class="circle ms-3 me-2 bg-danger"></div><span class="fst-italic">Dead trees percentage</span>
                </div>
                <div class="d-flex mt-3 mb-2">
                  <table class="table text-light fs-08 w-50">
                    <tbody>
                      <tr>
                        <td class="fst-italic fw-bold">• Alive trees</td>
                        <td><%= @alive_count %></td>
                      </tr>
                      <tr>
                        <td class="fst-italic fw-bold">• Dead trees</td>
                        <td><%= @dead_count %></td>
                      </tr>
                    </tbody>
                  </table>
                  <div class="card border-end border-bottom border-primary border-3 notscale rounded-4 bg-body ms-3 w-50">
                    <div class="card-body text-center fst-italic ">
                      <span class=""><%= message(@alive_count, @dead_count)%></span>
                    </div>
                  </div>
                </div>
            </div>
            <hr class="bg-body border-2 border-top">
            <div class="mt-3">
              <p class="m-0 fw-bold fst-italic">Tasks</p>
                <div class="d-flex justify-content-between">
                <div class="col-6 pe-2">
                  <table class="table text-light fs-08 mt-3">
                    <tbody>
                      <tr>
                        <td class="fst-italic fw-bold">• <span class="">Not started</span></td>
                        <td><%= @not_started_tasks %></td>
                      </tr>
                      <tr>
                        <td class="fst-italic fw-bold">• <span class="">In progress</span></td>
                        <td><%= @in_progress_tasks %></td>
                      </tr>
                      <tr>
                        <td class="fst-italic fw-bold">• <span class="">Completed</span></td>
                        <td><%= @done_tasks %></td>
                      </tr>
                    </tbody>
                  </table>
                  </div>
                  <div class="col-6">
                  <div class="card border-0 notscale rounded-4 bg-body ms-2">
                    <div class="card-body fs-07 py-3">
                      <p class="m-0 fs-08 fst-italic text-center mb-2">Number of tasks by status</p>
                      <%= pie_chart current_user.tasks.group(:status).count, height: "50px", legend: false, library: {animation: {easing: 'easeOutQuad'}, elements: {arc: {borderWidth: 0}}}, colors: ["#ff7979", "#badc58","#7ed6df"], empty: "Oops you haven't any task to see here!" %>
                      <div class="text-center fs-07 mt-2">
                        <span class="badge bg-danger rounded-4 px-1 text-dark fst-italic fw-bold">Not started</span>
                        <span class="badge bg-success rounded-4 px-1 text-dark fst-italic fw-bold">In progress</span>
                        <span class="badge bg-primary rounded-4 px-1 text-dark fst-italic fw-bold">Completed</span>
                      </div>
                    </div>
                  </div>
                  </div>

                </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <%# Aqui se renderizan las goals %>
    <div class="mt-5 pb-1 d-flex justify-content-between align-items-center border-bottom">
      <h5 class="m-0 p-0">Last updated goals</h5>
    </div>

    <div class="row mt-3 gx-3">
      <div class="col-8 rounded-4" data-controller="goal-modal">
        <% @last_updated_goals.each do |goal| %>
          <a href="" class="text-decoration-none link-light" data-bs-toggle="modal" data-bs-target="#modalGoal"
            data-bs-goal-name="<%= goal.name %>" data-bs-goal-maturity="<%= goal.maturity %>" data-bs-goal-description="<%= goal.description %>" data-bs-goal-category="<%= goal.category %>"
            data-bs-goal-date="<%= goal.completion_date %>" data-bs-goal-status="<%= goal.dead? %>" data-bs-goal-tasks-nostarted="<%= goal.tasks.not_started.count %>"
            data-bs-goal-tasks-inprogress="<%= goal.tasks.in_progress.count %>" data-bs-goal-tasks-done="<%= goal.tasks.done.count %>"
            data-bs-goal-url="<%= request.base_url %>/goals/<%= goal.id %>">
            <%= render 'card_goal_modal', goal: goal %>
          </a>
          <div class="modal fade mt-5" id="modalGoal" tabindex="-1" aria-labelledby="modalGoalLabel" aria-hidden="true">
            <%= render "modal_for_goal" %>
          </div>
        <% end %>
      </div>
      <div class="col-4">
        <div class="p-3 bg-secondary d-flex flex-column align-items-center justify-content-center rounded-4" style="height: 98%">
          <%= image_tag "explore_tree2.svg", width: "150px" %>
          <div class="mt-4">
            <span class="fw-bold">Let's explore your trees</span>
            <p class="fs-08 fst-italic my-2">See the forest created by you!</p>
          </div>
          <%= link_to "See all goals", goals_path, class: "mt-2 badge bg-primary text-decoration-none link-dark rounded-pill fs-08" %>
        </div>
      </div>
    </div>

  </div>

  <div class="col-md-4 order-0 order-md-1">
    <div class="position-sticky" style="top: 1rem;">
      <div class="px-3 pt-3 pb-1 mb-3 bg-secondary rounded-4">
        <h5 class="my-1 mb-3">Upcoming tasks</h5>
          <p class="fs-08"><%= @upcoming_tasks_day %></p>
          <% @upcoming_tasks&.each do |upcoming_task| %>
          <div class="col-12">
            <%= render 'tasks/partials/card_upcoming_task', task: upcoming_task %>

          </div>
          <% end %>
      </div>

      <div class="p-2 mb-3 bg-secondary rounded-4">
        <h5 class="mt-3 mb-2 px-2">Monthly calendar</h5>
        <div class="rounded-4 text-light">
          <%= render 'tasks/partials/calendar' %>
        </div>
      </div>
    </div>
  </div>


</div>

<% else %>

<div class="row" style="height: 80vh">
  <div class="col-12">
    <div class="notscale card border-0 bg-transparent" style="">
      <div class="card-body border-0 bg-transparent d-flex align-items-center justify-content-center">
        <div class="w-25">
          <%= image_tag "nothing.svg",
            class: "img-fluid bg-primary", style: "border-radius: 30% 70% 70% 30% / 54% 50% 50% 46%" %>
        </div>
        <div class="ms-4">
          <h5 class="card-title fs-4">Hmmm... nothing to see here! </h5>
          <p class="card-text text-end"><%= link_to "Why don't you create a new goal?", new_goal_path, class: "text-decoration-none link-warning fw-bold" %></p>
        </div>
      </div>
    </div>

  </div>
</div>
<% end %>
</div>