config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:index]

  root to: 'pages#home', as: :home
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Users
  get 'board', to: 'users#activity', as: :activity

  get 'get_json', to: 'goals#get_json'

  # Goals
  resources :goals, shallow: true do
    resources :tasks
      # member do
      #   patch :mark_as_done
      # end
  end

  resources :goals do
    resources :tasks, only: :show
  end
  get 'goals/category/:category', to: 'goals#by_category', as: :by_category
  get 'goals/status/:maturity', to: 'goals#by_status', as: :by_status
  # Tasks
  get '/tasks', to: 'tasks#all_tasks'
  patch '/tasks_update/:id', to: 'tasks#update_task'
  get '/calendar', to: 'tasks#calendar'
  get '/stats', to: 'tasks#stats'

  # Users - El nickname es unico para cada usuario
  resources :users, only: %i[show]
  # get 'u/:nickname', to: 'users#show'

  patch "goals/:goal_id/:task_id/mark", to: "tasks#done_task"
end

app/models/goal.rb
class Goal < ApplicationRecord
  include PgSearch::Model

  # after_create_commit :notify_user

  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_one_attached :photo
  has_rich_text :rich_body

  pg_search_scope :search,
                  against: %i[name description],
                  using: { tsearch: { prefix: true } }

  validates :name, :category, :user, presence: true
  validates :name, length: { minimum: 5, maximum: 60 }
  validates :description, length: { maximum: 200 }

  enum maturity: { baby: 0, young: 1, adult: 2 }

  # pockie_maturity = pockie.goals.group(:maturity).count
  # pockie_maturity.key(pockie_maturity.values.max)

  scope :by_status, ->(maturity) { where('maturity = ?', maturity) }

  # Fractions
  def not_started_tasks_fraction
    return tasks.not_started.count.fdiv(tasks.count) if tasks.count.positive?
  end

  def in_progress_tasks_fraction
    return tasks.in_progress.count.fdiv(tasks.count) if tasks.count.positive?
  end

  def done_tasks_fraction
    return tasks.done.count.fdiv(tasks.count) if tasks.count.positive?
  end

  def completed?
    done_tasks_fraction.to_d == 1.0.to_d
  end

  def dead?
    if tasks.present?
      last_task_date = tasks.order(:due_date).last.due_date
      done_tasks_fraction.to_d != 1.0.to_d && last_task_date < Date.today
    else
      false
    end
  end

  def dying?
    if tasks.present?
      last_task_date = tasks.order(:due_date).last.due_date
      done_tasks_fraction.to_d < 1.0.to_d && (last_task_date - Date.today).to_i <= 5
    else
      false
    end
  end

  def notify_user
    GoalNotification.with(goal: self).deliver_later(user)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: %i[show edit update destroy]
  before_action :new_goal, only: %i[index new]
  before_action :goal_policy, only: %i[show edit destroy]

  def index
    if params[:query].present?
      @pagy, @goals = pagy(current_user.goals.where("name like ?", "%#{params[:query]}%"))
    else
      @pagy, @goals = pagy(current_user.goals)
    end

    if turbo_frame_request?
      render partial: "goals", locals: { goals: @goals }
    else
      render :index
    end
  end

  def show
    @task = Task.new
    @todo = @goal.tasks.not_started
    @doing = @goal.tasks.in_progress
    @done = @goal.tasks.done

    # time = (6..17).include?(Time.now.hour) ? "night" : "day"
    @goal_tree = {
      id: @goal.id,
      maturity: @goal.maturity,
      status: @goal.dead? ? "dead" : "alive",
      landscape_type: "day",
      completed: @goal.completed?
    }.to_json
  end

  def get_json
    @goal = Goal.find(params[:goal_id])
    # time = (0..17).include?(Time.now.hour) ? "day" : "night"
    # goal_tree = {
    #   maturity: @goal.maturity,
    #   status: "dead",
    #   landscape_type: time,
    #   completed: false
    # }.to_json
    # render json: goal_tree
  end

  def by_status
    @goals = current_user.goals.by_status(params[:maturity])
  end

  def new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    @goal.save
    if @goal.save
      redirect_to goal_path(@goal)
    else
      render :new, status: :unprocessable_entity, alert: "Change a few things and try submitting again"
    end
  end

  def edit
  end

  def update
    @goal.update(goal_params)
    redirect_to goal_path(@goal), notice: "Your changes have been saved successfully"
  end

  def destroy
    @goal.destroy
    redirect_to goals_path, status: :see_other, notice: "Your goal has been deleted"
  end

  def by_category
    @goals = Goal.all
  end

  private

  def new_goal
    @goal = Goal.new
  end

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:name, :description, :category, :review, :maturity, :completion_date, :user_id)
  end

  def goal_policy
    set_goal
    redirect_to activity_path, alert: "You don't have permission to access this page" unless current_user == @goal.user
  end



end

app/views/goals/_button_modal_new_goal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-dark rounded-circle" data-bs-toggle="modal" data-bs-target="#newGoal">
  +
</button>
 <%= render 'goals/modal_new_goal' %>
<!-- End Button trigger modal -->

app/views/goals/_form_new_goal.html.erb
<div class="row justify-content-center mx-auto">

    <div class="d-flex justify-content-center">
      <% if @goal.name.nil? %>
      <h3>Create a New Goal</h3>
      <% else %>
       <h3>Edit Your Goal</h3>
       <% end %>
    </div>

    <div>
      <%= simple_form_for @goal do |f| %>

        <div class="row  m-2">
          <div class="row p-2 rounded-5 mb-3 bg-success text-dark bg-opacity-10">
            <div class="col-1 my-auto mx-auto d-flex align-items-center">
              <i class="fa-solid fa-cubes-stacked fs-1 mx-sm-1 mx-lg-5"></i>
            </div>
            <div class="col-10 pb-2">
              <h3>Goal title</h3>
              <%= f.input :name, input_html: {class: "border-0 rounded-4"},
                                             placeholder: "Enter goal title...", label:false %>
            </div>
          </div>
        </div>

        <div class="row  m-2">
            <div class="row p-2 rounded-5 mb-3 bg-success text-dark bg-opacity-10">
              <div class="col-1 my-auto mx-auto d-flex align-items-center">
                <i class="fa-solid fa-tag fs-1 mx-sm-1 mx-lg-5"></i>
              </div>
              <div class="col-10 pb-2">
                 <h3>Goal category</h3>
                  <%= f.input :category, input_html: {class: "border-0 rounded-4"},
                                                      placeholder: "Enter category to your goal...", label:false %>
              </div>
            </div>
        </div>

      <% unless @goal.name.nil? %>
        <div class="row col-12 mb-3">
          <%= f.input :description, input_html: {class:"border-1 rounded-4"}, size: "60x4", label: "Description", placeholder: "  Add a more detailed description..." %>
        </div>
      <% end %>

      <div class="row">
        <%= f.submit class:"btn btn-dark rounded-4"%>
      </div>

</div>
<% end %>

app/views/goals/_goal.html.erb
<div class="my-1 col-6 col-md-3" id="<%= dom_id goal %>">
 <%= link_to goal_path(goal), class:"text-decoration-none text-dark active" do %>
  <div class="card bg-secondary my-2 rounded-4 border-0 shadow-sm notscale border-end border-bottom border-primary border-1">
    <img src="<%= health_goal_image(goal.dead?, goal.maturity) %>" class="card-img-top rounded-bottom rounded-4 " alt="arbol">
    <div class="card-body text-light">
      <h5 class="card-title fs-6"><%= title_stylized(goal.name) %></h5>
      <h6 class="card-text text-muted fs-08 my-1"><span class="badge fs-09 text-bg-primary rounded-pill"><%= goal.category %></span></h6>
    </div>
  </div>
<% end %>
</div>

app/views/goals/_goals.html.erb
    <%= turbo_frame_tag "goals" do %>
    <div class="row">
      <%= render goals %>
    </div>
    <% end %>

app/views/goals/_list.html.erb
<div data-refresh-goals-list-target="list">
 <% @goals.each do |goal| %>
      <div class="card border-0 bg-secondary rounded-4 mb-2 notscale ">
        <div class="card-body d-flex justify-content-between py-2">
          <div class="">
            <h6 class="fs-5"><%= link_to goal.name, goal_path(goal), class: "text-decoration-none" %></h6>
            <h6 class="fs-08">Created at: <%= date_stylized(goal.created_at) %></h6>
            <h6 class="fs-07">Number of tasks: <%= goal.tasks.count %></h6>
          </div>

          <div class="d-flex justify-content-end align-items-start pt-2">
            <%= link_to edit_goal_path(goal), class: "text-decoration-none link-dark me-2" do %>
              <i class="bi bi-pencil-square rounded-circle p-1 bg-primary shadow-sm bg-gradient"></i>
            <% end %>
            <%= link_to edit_goal_path(goal), class: "text-decoration-none link-dark" do %>
              <i class="bi bi-trash3 rounded-circle p-1 bg-danger shadow-sm bg-gradient"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/goals/by_category.html.erb
<%= params[:category] %>

app/views/goals/by_status.html.erb
<div class="row mb-5">
  <%# Banner %>
  <div class="col-12 mb-4 bg-body sticky-top">
    <div class="d-flex align-items-end">
      <%= image_tag "tree_art.svg", class: "img-fluid", width: "150px" %>
      <div class="ms-4">
        <h2 class="fw-bold"><%= goal_status(params[:maturity]).capitalize %></h2>
        <p class="">Here you can find all your <%= goal_status(params[:maturity]) %>, which are represented by <%= @goals.first&.maturity %> trees.</p>
      </div>
    </div>
  </div>

  <div class="col-12 text-light" style="">
    <%# Datatable %>
    <div class="bg-secondary p-3 rounded-4">
        <table id="example" class="pt-3 table table-striped text-light display dataTable" style="width:100%" aria-describedby="example_info">
      <thead>
        <tr>
          <th class="sorting sorting_asc" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending">Goal</th>
          <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending">Tasks</th>
          <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending">Category</th>
          <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending">Created at</th>
          <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @goals.each do |goal| %>
        <tr class="">
          <td class=""><%= link_to goal.name, goal_path(goal), class: "text-decoration-none" %></td>
          <td><%= goal.tasks.count %></td>
          <td><span class="badge bg-info rounded-pill"><%= goal.category %></span></td>
          <td><%= date_stylized(goal.created_at) %></td>
          <td class="">
            <%= link_to edit_goal_path(goal), class: "text-decoration-none link-dark me-1" do %>
              <i class="bi bi-pencil-square rounded-3 p-1 bg-primary shadow-sm"></i>
            <% end %>
            <%= link_to edit_goal_path(goal), class: "text-decoration-none link-dark" do %>
              <i class="bi bi-trash3 rounded-3 p-1 bg-danger shadow-sm"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>

    </table>

    </div>

  </div>
</div>

app/views/goals/edit.html.erb
<!-- <div class="row justify-content-center align-middle mx-auto bg-success p-4 rounded-4" style="max-width: 40rem; height: auto;"> -->
<%= render 'goals/partials/form_new_goal' %>
<!-- </div> -->

app/views/goals/index.html.erb
<%# Banner %>
  <div class="col-12 mb-4 py-3 bg-body sticky-top">
<!-- Button back -->
    <div class="d-flex align-items-end me-4">
      <div class="back-btn mb-auto pt-1 me-4">
        <%= link_to :back do %>
            <i class="fa-solid fa-circle-arrow-left fs-2" class="back-btn rounded-4" data-bs-toggle="tooltip" data-bs-placement="top" title="Go Back"></i>
        <% end %>
      </div>
      <%= image_tag "goals-title.svg", class: "img-fluid", width: "130px" %>
      <div class="ms-4 d-flex justify-content-between align-items-end w-100">
        <div>
          <h2 class="fw-bold">Your trees</h2>
          <p class="m-0 "> Organize your goals and purposes! here you can see all your goals and add a new one.</p>
        </div>
        <%= link_to "Add a new goal", new_goal_path, class: "fs-08 badge bg-success text-dark text-decoration-none rounded-pill m-1 px-3 py-2" %>
      </div>
    </div>
  </div>


<div class="row g-4 pb-5 mt-3">
  <div class="col-md-12 order-1 order-md-0">

    <div class="col-12 mx-auto">
      <div class="col-12">
        <%= render 'goals/partials/form_search' %>
      </div>
    </div>
    <hr>

    <div class="row justify-content-center">
      <div class="col-12">
        <div class="row" data-masonry='{"percentPosition": true }' data-refresh-list-target="list">
          <%= render "goals", goals: @goals %>
        </div>

        <div class="col-12 d-flex justify-content-end my-3">
          <%= render 'goals/partials/bootstrap_nav', pagy: @pagy %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/goals/new.html.erb
<!-- <h3>Create a New Goal</h3> -->
<%= render 'goals/partials/form_new_goal' %>

app/views/goals/show.html.erb
<%# Tabs %>
<div>
<ul class="nav nav-tabs border-0 bg-transparent" id="myTab" role="tablist">
  <li class="nav-item" role="presentation" data-controller="get-goal-information">
    <button class="nav-link active" onclick="location.reload()" id="tree-goal-tab" data-bs-toggle="tab" data-bs-target="#tree-goal-tab-pane" type="button" role="tab" aria-controls="tree-goal-tab-pane" aria-selected="true"><i class="bi bi-signpost-fill me-2"></i>Tree</button>
    <input type="text" hidden value="<%= @goal.id %>" data-get-goal-information-target="goalId">
  </li>

  <li class="nav-item" role="presentation">
    <button class="nav-link" id="board-goal-tab" data-bs-toggle="tab" data-bs-target="#board-goal-tab-pane" type="button" role="tab" aria-controls="board-goal-tab-pane" aria-selected="false"><i class="fa-solid fa-grip me-2"></i>Board</button>
  </li>

  <li class="nav-item" role="presentation">
    <button class="nav-link" id="details-goal-tab" data-bs-toggle="tab" data-bs-target="#details-goal-tab-pane" type="button" role="tab" aria-controls="details-goal-tab-pane" aria-selected="false"><i class="bi bi-journal-bookmark me-2"></i>Notes</button>
  </li>
</ul>
</div>

<%# Banner goal %>
<div class="row mt-3 px-2 bg-body">
  <div class="col-12 rounded-4">
    <div class="d-flex justify-content-between align-items-center py-3">
        <h2 class="text-light fw-bold"><%= @goal.name %></h2>
        <div>
          <%= link_to edit_goal_path(@goal), class: "text-decoration-none link-dark circle-icon me-2" do %>
            <i class="bi bi-pencil-square rounded-circle p-2 bg-primary fw-bold fs-5 shadow-sm bg-gradient"></i>
          <% end %>
          <%= link_to goal_path(@goal), class: "text-decoration-none link-dark circle-icon", data: { turbo_method: :delete, controller: 'sweetalert', action: "click->sweetalert#show", sweetalert_title_value: @goal.name } do %>
            <i class="bi bi-trash3 rounded-circle p-2 bg-danger fw-bold fs-5 shadow-sm bg-gradient"></i>
          <% end %>
        </div>
    </div>
  </div>
</div>

<%# Tabs Content %>
<div class="tab-content mb-3 pb-3" id="myTabContent">

  <div class="tab-pane fade show active" id="tree-goal-tab-pane" role="tabpanel" aria-labelledby="tree-goal-tab" tabindex="0">
    <div class="row pb-5">

      <div class="col-12 col-md-4">
        <div class="p-2 bg-secondary rounded-4 border-3 border-end border-bottom border-primary">
          <div class="row">
            <div class="col-12 mx-4 mt-2">
              <div class="row">
                <div class="col-4">
                  <p class="fw-bold text-success m-0">Tree status:</p>
                </div>
                <div class="col-6">
                  <p class="fs-09"><%= health_goal(@goal) %></p>
                </div>
              </div>
            </div>
          </div>
          <% if @goal.description.present? %>
          <div class="row">
            <div class="col-12 mx-4 mt-2">
              <p class="mb-1 fs-09 fw-bold">Description</p>
            </div>
          </div>
          <div class="row">
            <div class="col-12 mx-4 mt-1">
              <p class="fs-08 opacity-75 mb-3"><%= @goal.description  %></p>
            </div>
          </div>
          <% end %>
          <div class="row mt-2 mx-2">
            <div class="col">
              <div class="row p-1 rounded-4 g-2 mb-3 text-light bg-body">
                <div class="col-3 my-auto mx-auto d-flex align-items-center justify-content-center text-primary">
                  <i class="fa-solid fa-tag text-warning"></i>
                </div>
                <div class="col-9 py-2">
                  <div>
                    <p class="fs-07 m-0 fw-bold text-warning">Category</p>
                  </div>
                  <div>
                    <p class="m-0 fs-07"><%= @goal.category %></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="row p-1 rounded-4 g-2 mb-3 text-light bg-body">
                <div class="col-3 my-auto mx-auto d-flex align-items-center justify-content-center text-primary">
                  <i class="fa-solid fa-clock text-primary"></i>
                </div>
                <div class="col-9 py-2">
                  <div>
                    <p class="fs-07 m-0 fw-bold text-primary">Completion date</p>
                  </div>
                  <div>
                   <p class="m-0 fs-07"> <%= date_stylized(@goal.completion_date) || "Open" %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row mt-2 mx-2">
            <div class="col">
              <div class="row p-1 rounded-4 g-2 mb-3 text-light bg-body">
                <div class="col-3 my-auto mx-auto d-flex align-items-center justify-content-center text-primary">
                  <i class="fa-solid fa-clipboard-list text-info"></i>
                </div>
                <div class="col-9">
                  <div>
                    <p class="fs-07 m-0 fw-bold text-info">Total tasks</p>
                  </div>
                  <div>
                    <p class="d-flex justify-content-center"><%= @goal.tasks.count %></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="row p-1 rounded-4 g-2 mb-3 text-light bg-body">
                <div class="col-3 my-auto mx-auto d-flex align-items-center justify-content-center text-primary">
                  <i class="fa-solid fa-hourglass text-danger"></i>
                </div>
                <div class="col-9">
                  <div>
                    <p class="fs-07 m-0 fw-bold text-danger">Not started</p>
                  </div>
                  <div>
                    <p class="d-flex justify-content-center"> <%= @goal.tasks.not_started.count %> </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row mt-2 mx-2">
            <div class="col">
              <div class="row p-1 rounded-4 g-2 mb-3 text-light bg-body">
                <div class="col-3 my-auto mx-auto d-flex align-items-center justify-content-center text-primary">
                  <i class="fa-solid fa-spinner text-primary"></i>
                </div>
                <div class="col-9">
                  <div>
                    <p class="fs-07 m-0 fw-bold text-primary">In progress</p>
                  </div>
                  <div>
                  <p class="d-flex justify-content-center"><%= @goal.tasks.in_progress.count %></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="row p-1 rounded-4 g-2 mb-3 text-light bg-body">
                <div class="col-3 my-auto mx-auto d-flex align-items-center justify-content-center text-primary">
                  <i class="fa-solid fa-circle-check text-success"></i>
                </div>
                <div class="col-9">
                  <div>
                    <p class="fs-07 m-0 fw-bold text-success">Done</p>
                  </div>
                  <div>
                  <p class="d-flex justify-content-center"> <%= @goal.tasks.done.count %> </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-12 col-md-8">
        <input type="text" hidden value="<%= request.url %>" id="urlTree">
        <div class="mx-auto" id="canvasTree" onload="location.reload()">
          <%= render "goals/tree/goal_tree", locals: { goal_tree: @goal_tree } %>
        </div>
      </div>
    </div>
  </div>

  <div class="tab-pane fade" id="board-goal-tab-pane" role="tabpanel" aria-labelledby="board-goal-tab" tabindex="0">
    <% unless @goal.dead? %>
      <div class="pt-3 px-3">
        <div class="d-flex align-items-center">
          <h4 class="m-0 me-3 ps-1">Tasks</h4>
          <%= link_to new_goal_task_path(@goal) do %>
            <i class="fa-solid fa-circle-plus fs-5"></i>
          <% end %>
        </div>
      </div>
    <%= render 'goals/partials/tasks_render_mobile', tasks: @goal.tasks %>
    <%= render 'tasks/partials/board_task_cards' %>
    <% else %>
      <div class="row">
        <div class="col-12">
          <div class="card notscale bg-body border-0">
            <div class="card-body d-flex justify-content-center align-items-center">
              <div class="w-25 me-5">
                <%= image_tag "heartbroken.svg", class: "img-fluid" %>
              </div>
              <div class="bg-secondary text-center p-3 rounded-4 border-end border-bottom border-primary border-3">
                <p class="fs-4 fw-bold text-primary">Oh oh!</p>
                <p class="fs-5 opacity-75">The task board is <span class="fw-bold">closed</span> for this goal</p>
                <p class="fs-5 opacity-75"><span class="text-warning fw-bold">Your tree is already dead!</span> Be careful the next time!</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="tab-pane fade" id="details-goal-tab-pane" role="tabpanel" aria-labelledby="details-goal-tab" tabindex="0">
    <div class="row ps-3">
      <div class="col-12">
        <div class="position-relative bg-secondary text-center border-0 p-3 rounded-4 rounded-bottom">
          <h6 class="fs-2 mt-2">Notes</h6>
          <%# <div class="position-absolute clip-rich-text"><i class="bi bi-paperclip display-4 text-success"></i></div> %>
        </div>
        <div class="card border-0 bg-secondary text-light px-4 py-3 notscale rounded-4 rounded-top">
          <%= simple_form_for @goal, class: "" do |f| %>
            <%= f.rich_text_area :review, as: :file, input_html: { class: "shadow-sm customized-min-height" } %>
            <div class="d-flex justify-content-end pt-2">
              <%= f.submit "Save note", class:"btn btn-link link-light border-bottom border-2 text-decoration-none p-1"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<script>
if(!window.location.hash.includes("#reloaded")) {
    window.location.href += "#reloaded";
    window.location.reload()
}
</script>