config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:index]

  root to: 'pages#home', as: :home
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Users
  get 'board', to: 'users#activity', as: :activity

  get 'get_json', to: 'goals#get_json'

  # Goals
  resources :goals, shallow: true do
    resources :tasks
      # member do
      #   patch :mark_as_done
      # end
  end

  resources :goals do
    resources :tasks, only: :show
  end
  get 'goals/category/:category', to: 'goals#by_category', as: :by_category
  get 'goals/status/:maturity', to: 'goals#by_status', as: :by_status
  # Tasks
  get '/tasks', to: 'tasks#all_tasks'
  patch '/tasks_update/:id', to: 'tasks#update_task'
  get '/calendar', to: 'tasks#calendar'
  get '/stats', to: 'tasks#stats'

  # Users - El nickname es unico para cada usuario
  resources :users, only: %i[show]
  # get 'u/:nickname', to: 'users#show'

  patch "goals/:goal_id/:task_id/mark", to: "tasks#done_task"
end

app/views/shared/navbars/_navbar.html.erb
<nav class="navbar shadow-sm navbar-expand-lg">
  <div class="container-fluid mx-2 py-0">

    <%= link_to image_tag("https://res.cloudinary.com/dknxl9ghi/image/upload/v1667572387/logo_vec_sx4wzo.png", :style => 'width: 5.7rem;'), activity_path %>
    <ul class="navbar-nav ms-auto">
      <div class="d-flex">
        <%# Notifications %>
        <%#= render "shared/navbars/notifications" %>

        <%# User actions %>
        <a class="nav-link" href="#" data-bs-toggle="dropdown">
          <%= image_tag get_avatar_url, class: "avatar avatar-sm dropdown-toggle", id: "navbarDropdown", 'aria-haspopup': true, 'aria-expanded': false %>
        </a>

        <ul class="bg-body dropdown-menu dropdown-menu-dark dropdown-menu-end mx-4 me-3 position-absolute mt-1 border-0 rounded-4 shadow-sm" tab-index="-20">
          <%= link_to user_path(current_user), class: "text-decoration-none link-light" do %>
            <li class="dropdown-item rounded-3">
                <i class="bi bi-person-circle me-3"></i>
                <span>Profile</span>
            </li>
         <% end %>

          <%#= link_to "#", class: "text-decoration-none link-light" do %>
            <%# <li class="dropdown-item rounded-3">
              <i class="bi bi-bar-chart-line me-3"></i>
              <span>Activity</span>
            </li> %>
          <%# end %>

          <li><hr class="dropdown-divider"></li>
          <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "text-decoration-none link-light" do %>
            <li class="dropdown-item rounded-3 mb-1">
              <i class="bi bi-power me-3"></i>
              <span>Log Out</span>
            </li>
          <% end %>
        </ul>
      </div>
    </ul>
  </div>
</nav>

app/views/shared/navbars/_notifications.html.erb
<a href="#" class="nav-link me-2 my-auto text-light" data-bs-toggle="dropdown">
  <i class="bi bi-bell fs-4"></i>
</a>

<ul class="bg-body text-light dropdown-menu dropdown-menu-end position-absolute mt-1 me-4 border-0 rounded-4 shadow-sm p-3" style="max-width: 20rem;">
  <li><h6 class="dropdown-header px-0 text-light">Notifications</h6></li>
  <%= turbo_frame_tag "notifications", src: notifications_path %>
  <%= turbo_stream_from current_user, :notifications %>
</ul>

app/views/shared/navbars/_sidebar.html.erb
<aside class="sidebar p-sm-1 shadow-sm align-items-center">
  <ul class="sidebar-list m-0 p-0 mx-lg-2">

    <li class="mt-sm-2 mb-sm-2 p-2">
      <%= link_to activity_path, class: "nav-link d-flex align-items-center" do %>
        <i class="opacity-75 bi bi-columns-gap"></i>
        <span class="d-none d-md-inline ms-2 opacity-75 fw-bold">Dashboard</span>
      <% end %>
    </li>

    <hr class="my-2 d-none d-sm-block text-light border-3">

    <li class="mb-sm-2 p-2">
      <%= link_to goals_path, class: "nav-link d-flex align-items-center" do %>
        <i class="opacity-75 bi bi-compass"></i>
        <span class="d-none d-md-inline ms-2 opacity-75 fw-bold">Goals</span>
      <% end %>
    </li>

    <li class="mb-sm-2 p-2">
      <%= link_to tasks_path, class: "nav-link d-flex align-items-center" do %>
        <i class="opacity-75 bi bi-list-task"></i>
        <span class="d-none d-md-inline ms-2 opacity-75 fw-bold">Tasks</span>
      <% end %>
    </li>

    <li class="mb-sm-2 p-2">
      <%= link_to calendar_path, class: "nav-link d-flex align-items-center" do %>
        <i class="opacity-75 bi bi-calendar-minus"></i>
        <span class="d-none d-md-inline ms-2 opacity-75 fw-bold">Calendar</span>
      <% end %>
    </li>

    <li class="mb-sm-2 p-2 d-none d-sm-block">
      <%= link_to stats_path, class: "nav-link d-flex align-items-center" do %>
        <i class="opacity-75 bi bi-graph-up"></i>
        <span class="d-none d-md-inline ms-2 opacity-75 fw-bold">Stats</span>
      <% end %>
    </li>

  </ul>
</aside>